---
title: "Exploratory"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
library(ggplot2)
library(MASS)
source('./R/death_plot_fun.R')
source('./R/Format_US_Population.R')
```

```{r}
pneumo.deaths <-   readRDS('./Data/pneumococcal_deaths_line_list.rds')

pneumo.deaths$agec <- factor(pneumo.deaths$agec, c("Under 5 Years",'5-24 years', "25-44 years","45-64 years","65-74 years" ,"75-84 years","85 years and older"))

pneumo.deaths$race_recode <- factor(pneumo.deaths$race_recode, levels=c(1,2,3,4,5), c('White','Black','Hispanic','American Indian', 'Asian/Pacific Islanders')) 
```

Popsize data
```{r}
#Format_US_Population()
pop1 <- readRDS('./Data/pop_interpol.rds')

pop2 <- pop1 %>%
  group_by(date, agec, race_recode) %>%
  summarize(pop.interpol= sum(pop.interpol)) %>%
  mutate(race_recode= factor(race_recode,levels=c(1,2,3,4,5), c('White','Black','Hispanic','American Indian', 'Asian/Pacific Islanders')))
```


```{r}
sort(table(pneumo.deaths$icd1), decreasing=T)[1:100]
```

```{r}
pneumo.prim <- pneumo.deaths %>%
  filter(icd1 %in% c('A403','J13','B953','G001'))
table(pneumo.prim$icd1, pneumo.prim$agec)

table(pneumo.prim$icd1, pneumo.prim$race_recode)

```


```{r}
sort(table(pneumo.deaths$icd2), decreasing=T)[1:100]
```

```{r}
p1 <- death_plot_fun(year,month)
p1$plot1
```

```{r}
p2 <- death_plot_fun(year,month, agec) 
p2$plot1 + facet_wrap(~agec, scales='free')
```
Note; big differences in age distribution. Hispanic skews much younger
```{r}
p3 <- death_plot_fun(year,month, race_recode) 
p3$plot1+ facet_wrap(~race_recode, scales='free')
```


Age of deaths, by race/ethnicity. The proportion of deaths among kids is much higher for Black and Hispanic populations. need to look at incidence by age
```{r}
 p1 <- ggplot(pneumo.deaths, aes(x=agey))+
  geom_histogram() +
  theme_classic() +
  facet_wrap(~race_recode, scales='free_y')
p1
```
```{r}
p3 <- death_plot_fun(year,month, race_recode, agec) 

p3$ts$date <- as.Date(paste(p3$ts$year, p3$ts$month, '01',sep='-') , '%Y-%m-%d' )


p3.ds <- merge(p3$ts, pop2, by=c('agec','race_recode', 'date')) %>%
  group_by(race_recode, agec) %>%
  summarize(N_deaths=sum(N_deaths), pop=mean(pop.interpol))%>%
  ungroup() %>%
  mutate(inc=N_deaths/pop*100000 , race_recode=factor(race_recode)) 

ggplot(p3.ds, aes(x=agec, y=log(inc), group=race_recode,col=race_recode)) +
  geom_line()+
  theme_classic()+
  ggtitle('Rate of death by age and race/ethnicity')+
   theme(axis.text.x = element_text(angle = 45, vjust = 0.9, hjust=1)) +
  ylab('Deaths/100,000') +
  xlab('')
```


## Question 1: Did the rate of death due to pneumococcus change during the pandemic?

Fit model to 2014-2019 data, extrapolate to 2020 and beyond

```{r}
ds1 <- p1$ts %>%
  mutate(date=as.Date(paste(year, month, '01', sep='-')),
         qtr=as.factor(lubridate::quarter(date)),
         index= interval('2014-01-01', date) %/% months(1) ,
         sin12 = sin(2*pi*index/12),
         cos12 = cos(2*pi*index/12),
         sin6 = sin(2*pi*index*2/12),
         cos6 = cos(2*pi*index*2/12),
         N_deaths_pre= if_else(year %in%'2020', NA_real_,N_deaths),
         log_offset=log(1))


mod1 <- glm(N_deaths_pre ~ index+ sin12+cos12 +sin6 +cos6, 
            data=ds1, family='poisson')


mod2 <- glm.nb(N_deaths_pre ~ index+ sin12+cos12 +sin6 +cos6, 
            data=ds1)

ds1 <- cbind.data.frame(ds1,pred_interval(mod=mod1,model.type='poisson'))

ggplot(data=ds1, aes(x=date, y=N_deaths)) +
  geom_line() +
  theme_classic()+
    geom_ribbon(aes(ymin=pred_lcl, ymax=pred_ucl), alpha=0.2)


ds1 <- ds1 %>%
  mutate(rr_median=N_deaths/pred_median, rr_lcl=N_deaths/pred_lcl, rr_ucl=N_deaths/pred_ucl)


ggplot(data=ds1, aes(x=date, y=rr_median)) +
  geom_line() +
  theme_classic()+
    geom_ribbon(aes(ymin=rr_lcl, ymax=rr_ucl), alpha=0.2)+
  ylim(0.5,2.2) +
  geom_hline(yintercept=1, lty=2, col='gray')

```


